---
- name: 레포 클론
  git:
    repo: https://github.com/woowa-beavers/woowa-beavers-shop.git
    dest: /app/woowa-beavers-shop
    version: main
    force: yes

- name: .env 파일 복사
  template:
    src: env.j2
    dest: /app/woowa-beavers-shop/.env
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Docker Compose 실행
  shell: |
    cd /app/woowa-beavers-shop
    docker-compose up -d {{ service_name }}
  become: yes
